### ISSUE TITLE
Clip deprecated 

### ISSUE THREAD

**Issue by potts99** [nerdyman/react-compare-slider#113]
Hiya, 

Looking to use your library in a project and we've noticed some out of date things like react 16 and usage of CLIP. 

https://developer.mozilla.org/en-US/docs/Web/CSS/clip

Is there any chance of getting this updated to clip-path? is there a new release coming soon i see you are working on some stuff

**Comment by nerdyman** [comment]
Hey Jack, thanks for opening the issue!

v3 uses `clip-path` so this should be resolved soon (probably a week or so). I've just got to sort some things with Storybook and do some perf testing and it'll be good to go. There will be a pre-release version released before the main release so I'll post here when it's released if you'd like to give it a go. The API for v3 is compatible with v2 so there shouldn't be any issues if you install v2 for now and upgrade to v3 later.

React `>=16.8` is a peer dep so the lib will use whichever version of React you have installed. It should only complain if you're using a version older than `16.8`,  are you seeing any issues with newer versions of React?

**Comment by nerdyman** [comment]
This has been released in [v3](https://github.com/nerdyman/react-compare-slider/releases/tag/v3.0.0)!

```bash
npm install react-compare-slider@latest
yarn add react-compare-slider@latest
pnpm install react-compare-slider@latest
```
