### ISSUE TITLE
Scroll issue on mobile devices after "touch-action: none" styling

### ISSUE THREAD

**Issue by ins2718** [nerdyman/react-compare-slider#134]
Hello everyone, I wanted to bring to your attention an issue that arose in one of the commits early in 2023 ([Commit Link](https://github.com/nerdyman/react-compare-slider/commit/87ba39ee9258eaaf1ff3b8483f38f03db9c7c83a)).

In this commit, the widget received the style property "touch-action: none", resulting in the disruption of scrolling on relevant devices. This has become a critical issue, especially on mobile phones, where the widget might occupy a significant portion of the screen.

**Comment by LefanTan** [comment]
You can get around this by adding ` style={{ touchAction: "pan-y" }}` to the component

**Comment by nerdyman** [comment]
Thanks @ins2718 & @LefanTan,

I did add `touch-action: none` for a reason though I can't remember why now, might have been a Firefox issue. I'll take a look at a fix.

**Comment by ins2718** [comment]
> You can get around this by adding ` style={{ touchAction: "pan-y" }}` to the component

Yes, I fixed it by adding the class !touch-pen-y (tailwind). However, this issue was discovered accidentally and is not present on the demo pages. Therefore, I assume it's more likely a bug and should be reported.

**Comment by nerdyman** [comment]
`touch-action: none` was added to avoid the slider 'disconnecting' when you drag back and forth on touch devices. E.g. if you drag back and forth on Safari iOS without the style applied the slider will stop sliding if your finger or thumb isn't completely on the screen. I'll see if there's a better way to keep it sliding while dragging without stopping general scrolling - the style might just need to be applied while the slider is in the dragging state.

**Comment by nerdyman** [comment]
`pan-y` is now the default in v4. I need to do testing on other devices before doing a final release but there is a pre-release ready to go.

It can be installed by running:

```sh
pnpm i react-compare-slider@beta
# Or
yarn add react-compare-slider@beta
# Or
npm i react-compare-slider@beta
```
