### ISSUE TITLE
Add support for clipping imageOne

### ISSUE THREAD

**Issue by zoltan-mihalyi** [nerdyman/react-compare-slider#136]
Right now only imageTwo is clipped. Comparing two semi-transparent images would be a useful function.

**Comment by nerdyman** [comment]
@zoltan-mihalyi Ah yeah I ran into this myself with the images used in the readme. I'll take a look at clipping both.

**Comment by nerdyman** [comment]
This has been resolved in v4. I need to do testing on other devices before doing a final release but there is a pre-release ready to go.

It can be installed by running:

```sh
pnpm i react-compare-slider@beta
# Or
yarn add react-compare-slider@beta
# Or
npm i react-compare-slider@beta
```
