### ISSUE TITLE
Is it possible to use another html tag for slider role?

### ISSUE THREAD

**Issue by spiletski** [nerdyman/react-compare-slider#147]
Hello, 
Using the library in storybook an accessibility issue is appeared. 
On accessibility tab: 
https://dequeuniversity.com/rules/axe/4.8/aria-allowed-role?application=axeAPI

<img width="747" alt="image" src="https://github.com/nerdyman/react-compare-slider/assets/31621040/9cafcc45-3bf6-4973-86a3-35d25acbbb58">

<img width="844" alt="image" src="https://github.com/nerdyman/react-compare-slider/assets/31621040/6697783c-0e5a-4f88-93ec-eca4cd2be6f9">

The issue is related to using <button> and role='slider'. Is it possible to replace the button with div for example?

Thanks in advance!

**Comment by nerdyman** [comment]
[Lighthouse also uses axe-core](https://github.com/GoogleChrome/lighthouse/blob/c977fe8f25b2fc6a7384b30a9351ea061f52c3bb/package.json#L184) so this issue should resolve when the dependencies are upgraded.

Feel free to reopen it if it's still an issue after upgrading.
