### ISSUE TITLE
Synchronizing two sliders - is it possible?

### ISSUE THREAD

**Issue by Mahrryie** [nerdyman/react-compare-slider#18]
Hi!
I want to implement next feature - while dragging the handler of  the first slider the other slider changes simultaneously according to motion of the first one
Is it possible to embody?

**Comment by nerdyman** [comment]
Hi @Mahrryie, thanks for opening the issue.

It is somewhat possible to do this with the current implementation by using a central state object which is updated when the position changes on either of the slider components but this would cause quite a lot of re-rendering and processing.

I've got changes in mind on the `next` branch which would allow this functionality (and lots more) but it will require a significant change to the way props are managed.

I'm looking at creating a hook which accepts all the current props and returns the props needed for the `ReactCompareSlider` component. The hook would replace the [internal function](https://github.com/nerdyman/react-compare-slider/blob/master/src/react-compare-slider.tsx#L186) used to set the slider position via the `setPosition` prop in the hook.

The pattern would something like:

```typescript
const useReactCompareSliderState = (props) => {
    // Replaces `updateInternalPosition` function in `ReactCompareSlider.tsx`
    const setPosition = useCallback(({ ref, x, y }) => {
        // - Calculate the current position base on `ref`s bounding box
        // - Use `x` for landscape and `y` for portrait
        // - Update styles directly on ref
    }, []);
    
    return {
        ...props,
        setPosition,
    };
};
```

```typescript
const Component = () => {
  const reactCompareSliderState = useReactCompareSliderState({
    position: 20,
    onPositionChange: position => {/*...*/}
    // ...and any other props
  });

  return <ReactCompareSlider {...reactCompareSliderState} />;
};
```

This would cover your use case of wanting to link the state of two sliders as you could do something like:

```typescript
const Component = () => {
  const reactCompareSliderState = useReactCompareSliderState({
    position: 20,
    // ...and any other props
  });

  return (
    <>
      <ReactCompareSlider {...reactCompareSliderState} />
      <ReactCompareSlider {...reactCompareSliderState} />
    </>
  );
};
```

It still needs a bit more thought, the most recent release of the library replaced the state re-renders with ref based updates so it would be good to stick to refs if possible but I haven't looked into enough yet to see if there's a clean solution which would allow the same state to be shared across multiple sliders.

[`useImperativeHandle`](https://reactjs.org/docs/hooks-reference.html) may be an option too as it could be used to expose the internal position function to the parent, which you could then call using the `onPositionChange` callback on the sliders. It might be better than the custom hook option as the props can stay the same and an optional ref could be passed to the slider component when you want to update the internal position yourself.

Do you have any suggestions on how to handle syncing the states between sliders?  It doesn't need to be the same as what I've suggested above, I'm open to suggestions :)

**Comment by Mahrryie** [comment]
I've done it that way:
const [cPosition, setCPosition] = useState(50); // that's the initial position of the hadler since it looks good that way

and into both sliders i've implemented such values
position={cPosition} 
onPositionChange={setCPosition}

since they're identical and set beforehand, the components receive same props and change synchronously

**Comment by nerdyman** [comment]
No need to apologise @Mahrryie It's my bad :) I went too deep into future changes without giving an example of how to do it with the current version.

I've [created an example here](https://codesandbox.io/s/eloquent-lalande-5474p?file=/src/App.tsx) to demonstrate how it can work (using your method posted above). Something to keep in mind is to ensure the `onPositionChange` callback function is wrapped in `useCallback` as it's used as a dependency inside the slider library and will cause more re-renders if it's not in `useCallback`. 

The performance isn't as bad as I thought but it's not as performant as a single slider because it's doing double the work *and* also re-rendering to keep the positions in sync. This will be improved in a future release.

Thanks for opening the issue, I'll also add an example controlling two sliders the docs.
