### ISSUE TITLE
How do differently sized images scale in sync?

### ISSUE THREAD

**Issue by wKich** [nerdyman/react-compare-slider#19]
Hello. Thanks for staring ⭐  `Creevey`. I see you made nice looking react compare slider. In `Creevey` I made something similar in [SlideView](https://github.com/wKich/creevey/blob/master/src/client/shared/components/ImagesView/SlideView.tsx#L88), but less powerful and based on native `input[type=range]` with a few styles. Could you tell how your implementation handle images with different sizes?

**Comment by nerdyman** [comment]
Hi @wKich thanks for opening the issue, Creevey looks dope btw!

The different image sizes are handled by absolutely positioning one image on top of the other within a relative container. Both images us `width: 100%; height: 100%; object-fit: cover;` so they fill their container and maintain their aspect ratio. This means that the smaller of the two always gets scaled up and cropped.

[Here's an example using `1440x300` and `1280x720`](https://codesandbox.io/s/divine-http-9e175?file=/src/App.tsx).

If you're interested I'd be happy to open a pull request in Creevy to use this library.

**Comment by wKich** [comment]
Hi. Thanks for explanation. For Creevey, I need a little different behavior, where images don't cropped and placed on top left corner. Because that's how I generate diff image by using [https://github.com/mapbox/pixelmatch](pixelmatch). But the main issue for slider is to use same scale for two images. For example, if image A wider than image B, and image A don't fit into container and scaled-down by 1.5x times, when I need to scale-down image B by 1.5x too, both images should be placed on top-left corner of the container.

I known, it's not perfect solution for some edge cases. But when I have only images without context of what element has been captured I use pretty straid-forward algorithm, place both images in top-left corner and compare each pixel. When I capture new screenshot and it has different size it's more likely some content has been added/removed on right or bottom of the original screenshot image.

It would be really great if you send a PR :)

**Comment by nerdyman** [comment]
Thanks for the info @wKich, I think I understand the issue. It's possible to position and not crop the images by doing the following:

```js
<ReactCompareSliderImage
	style={{ objectFit: 'contain', objectPosition: 'left top' }}
/>
```

The library currently uses `itemTwo` to determine the size of the slider so some tweaking might be needed to fit your use case. The scaling of the images is a bit more tricky and might be better handled outside of the library.

I'll pull down Creevey and see if I can work something out :)

**Comment by wKich** [comment]
This looks cool. I didn't know about objectPositon style. My implantation don't handle scaling in proper way, I use workaround by placing transparent diff image.

Handling scale outside of the library it's ok. If you have any issues or questions with starting creevey on your PC, feel free to ask. I want to hear any feedback )
