### ISSUE TITLE
Is there a way to control the slider position using the keyboard?

### ISSUE THREAD

**Issue by lucianourgal** [nerdyman/react-compare-slider#31]
This would be interesting because of accessibility issues.

**Comment by nerdyman** [comment]
Hi @lucianourgal, thanks for opening this issue!

The library doesn't currently provide keyboard bindings but I'm definitely onboard with implementing some functionality or accepting a PR. I looked into briefly before but was unsure on how to make the component properly accessible (with the correct aria tags etc.).

With the current version it's possible to implement your own keyboard functionality add a `tabIndex` to the slider component to make it foscuable and then updating the `position` property on the slider when keyboard left, right, up, or down is pressed.

Here's a super basic demo listening to the `ArrowLeft` and `ArrowRight` `keydown` events to move the slider position left or right when the slider has focus.

- https://vspw1.csb.app/
- https://codesandbox.io/s/react-compare-slider-simple-example-forked-vspw1?file=/src/App.jsx:210-256

**Comment by lucianourgal** [comment]
Thank you @nerdyman, it worked!

**Comment by nerdyman** [comment]
Awesome! Thanks for opening the issue, I'll see if there's a clean way to add this to library in future.

**Comment by moloko** [comment]
Apologies for commenting on a closed issue, but just wanted to suggest that alternative way to do this would be to include an [HTML 'range' `<input>` element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/range) that's visually hidden but could still be accessed by assistive tech. As this is a standard HTML element it shouldn't require any extra work to make it accessible.

I'm going to be using this component on a project I'm working on which will need to have accessibility support - so I plan to try something along these lines.

Really nice component btw, thanks for making this available.

**Comment by nerdyman** [comment]
That's a good shout @moloko! Let me know how it goes, I'm totes up for improving accessibility.

**Comment by nerdyman** [comment]
This has been released in [v3](https://github.com/nerdyman/react-compare-slider/releases/tag/v3.0.0)!

```bash
npm install react-compare-slider@latest
yarn add react-compare-slider@latest
pnpm install react-compare-slider@latest
```
