### ISSUE TITLE
README: specifically call-out that this doesn't support IE11 any more

### ISSUE THREAD

**Issue by moloko** [nerdyman/react-compare-slider#44]
It's mentioned in the release notes for [v2.0.1](https://github.com/nerdyman/react-compare-slider/releases/tag/v2.0.1) but obviously it's easily missed in there.

Luckily I'm not in a position where the ImageSlider component itself needed to be functional in IE11, I just needed to make sure it didn't stop any project that included the code from even running in IE11...!

**Comment by nerdyman** [comment]
Good shout! I'll add a browser support section to the readme in [this pull request](https://github.com/nerdyman/react-compare-slider/pull/43).

**Comment by nerdyman** [comment]
@moloko This has been published in [v2.0.3](https://github.com/nerdyman/react-compare-slider#requirements)
