### ISSUE TITLE
"ReferenceError: document is not defined" in SSR

### ISSUE THREAD

**Issue by frepps** [nerdyman/react-compare-slider#6]
Hello, and thank you for your work on this component! 

I get a "document is not defined" error on the server when I am using server side rendering. 

It looks like the problem is here: 
https://github.com/nerdyman/react-compare-slider/blob/0729b0be3197f78d797575162f801055d7c54020/src/react-compare-slider.tsx#L143

I tried to fork the project an replace
`const containerRef = useRef<HTMLDivElement>(document.createElement('div'));`
with
`const containerRef = useRef<HTMLDivElement>(null);`
and add null-checks whenever `containerRef.current` is used, but my experience with typescript is limited and I didn't want to make a mess! 😀

**Comment by nerdyman** [comment]
Hi @frepps, thanks for opening the issue!

I'll need to change a few things to get it working with SSR since the library uses `document` and `window` in several places. I'll get cracking on a fix.

**Comment by nerdyman** [comment]
@frepps SSR support has been added in `1.0.3`, thanks for reporting the issue!
