### ISSUE TITLE
Is there a way on mouse leave return to initial position?

### ISSUE THREAD

**Issue by theexplay** [nerdyman/react-compare-slider#64]
Hello, Is there a way on mouse leave return to initial position?  It would be great if there was an API like this.

Now i'm using react key to rerender on mouse leave

**Comment by nerdyman** [comment]
Hey @theexplay, thanks for opening the issue!

It's not currently possible to reset the position back to the original from the parent due [how prop updates are handled](https://github.com/nerdyman/react-compare-slider/blob/45f52b3d4bf1a906ba75ea739d9f15091373d8c0/src/ReactCompareSlider.tsx#L186), but it's definitely a valid use case.

Using a key is probably the best way to do it for now, or set it to something like `50.0001`, but I'm open to suggestions on how to achieve it without hacks. 

I was thinking of exposing the `setInternalPosition` function to the parent using a hook or ref but haven't decided on the best approach yet. It might also be possible to refactor the logic in the link above to respect the parent position but I don't think the `useEffect` will be triggered if the `position` prop passed to the parent on mouse leave is the same value as the current `position`.

**Comment by theexplay** [comment]
I like the idea of providing api `updateInternalPosition` via ref

**Comment by nerdyman** [comment]
This has been released in [v3](https://github.com/nerdyman/react-compare-slider/releases/tag/v3.0.0)!

See the [`useReactCompareSliderRef` example](https://react-compare-slider.vercel.app/?path=/story/demos--use-react-compare-slider-ref) for usage.

```bash
npm install react-compare-slider@latest
yarn add react-compare-slider@latest
pnpm install react-compare-slider@latest
```
