### ISSUE TITLE
useLayoutEffect warning

### ISSUE THREAD

**Issue by samantha-wong** [nerdyman/react-compare-slider#8]
Hi I'm getting this error when using react-compare-slider on my nextjs project :

useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client.

**Comment by nerdyman** [comment]
Hi @samantha-wong, thanks for reporting the issue!

I'll look at getting a fix in.

**Comment by nerdyman** [comment]
@samantha-wong This has been fixed in `1.0.4`, feel free to reopen the issue if it's still a problem.

**Comment by samantha-wong** [comment]
@nerdyman Thanks for fixing it so quickly! It's being used here if you're interested: https://pory.io :)

**Comment by nerdyman** [comment]
@samantha-wong No problem at all! Thanks for sharing the link, it's awesome to see it in the wild :smile:
