### ISSUE TITLE
Add prettier sort import order plugin

### ISSUE THREAD

**Issue by nerdyman** [nerdyman/react-compare-slider#84]
Use https://github.com/IanVS/prettier-plugin-sort-imports to sort imports with prettier and run prettier on entire repo.

**Comment by nerdyman** [comment]
Thanks for sorting this @raphaelts3, just tagging you here so I can assign the issue to you.

**Comment by raphaelts3** [comment]
Hey, @nerdyman I've pushed the https://github.com/nerdyman/react-compare-slider/pull/88 that tackles this one. 🙇
